trigger:
  branches:
    include:
      - main
      - feature/*
 
  paths:
    include:
    - terraform/prod/


variables:     
  my-dir: '$(System.DefaultWorkingDirectory)/terraform/prod'
  svc: 'MyNewSVC'

pool: Agent-Ka-Jhund

stages:
- stage: build 
  displayName: build
  jobs:
  - job: init_planw
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      displayName: 'Terraform init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: $(my-dir)
        backendServiceArm: $(svc)
        backendAzureRmStorageAccountName: 'stg131311'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'prod.tfstate'
    - task: TerraformTask@5
      displayName: 'Terraform plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: $(my-dir)
        environmentServiceNameAzureRM: $(svc)


- stage: scan
  displayName: scanning
  # condition: eq(parameters.scanningreq, 'true')
  jobs:
  - job: scanning
    steps:
    - task: tfsec@1
      inputs:
        version: 'v1.26.0'
        dir: '$(System.DefaultWorkingDirectory)/terraform/prod'

- stage: deploy
  displayName: deploy
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
  jobs:
    - job: manual_validation
      pool: server
      steps:
      - task: ManualValidation@1
        inputs:
          notifyUsers: 'snl.dby@gmail.com'
          approvers: 'snl.dby@gmail.com'



    - job: apply
      displayName: Apply
      pool: Agent-Ka-Jhund
      dependsOn: Manual_validation
      steps:
      - task: TerraformInstaller@1
        inputs:
         terraformVersion: 'latest'

      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/prod'
          backendServiceArm: 'MyNewSVC'
          backendAzureRmStorageAccountName: 'stg131311'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: 'prod.tfstate'
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/prod'
          environmentServiceNameAzureRM: 'MyNewSVC'
